config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "home/about"=>"homes#about",as:"about"
  resources :books,only:[:index,:show,:edit,:update,:create,:destroy]
  resources :users,only:[:index,:show,:edit,:update]
  root to:"homes#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title,presence: true
  validates :body,presence: true,length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books,dependent: :destroy
  has_one_attached :profile_image

  validates :name,presence: true,uniqueness: true,length: {minimum: 2,maximum: 20}
  validates :introduction,length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join("app/assets/images/sample-author1.jpg")
      profile_image.attach(io: File.open(file_path), filename: "default-image.jpg", content_type: "image/jpeg")
    end
   profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters,if:  :devise_controller?
  before_action :authenticate_user!, except: [:top,:about]
  
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:email])
      # devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book =Book.new(book_params)
    @book.user_id =current_user.id
   if @book.save
    redirect_to book_path(@book.id),notice: "You have created book successfully."
   else
    @books = Book.all
    render :index
   end
  end

  def index
    @book =Book.new
    @books =Book.all
  end

  def show
    @newbook=Book.new
    @book =Book.find(params[:id])
  end

  def edit
    @book =Book.find(params[:id])
   if @book.user == current_user
     render :edit
   else
     redirect_to books_path
   end
  end
  def update
    @book =Book.find(params[:id])
    if @book.update(book_params)
       redirect_to book_path,notice: "You have updated book successfully."
    else
      render :edit
    end
  end
  def destroy
    @book =Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end
  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  def about
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users =User.all
    @book = Book.new
  end
  def show
    @user =User.find(params[:id])
    @books = @user.books
    @book =Book.new
  end

  def edit
    @user =User.find(params[:id])
   if @user == current_user
    render :edit
   else
    redirect_to user_path(current_user)
   end
  end
  def update
   @user =User.find(params[:id])
   if @user.update(user_params)
     redirect_to user_path,notice: "You have updated book successfully."
   else
    render :edit
   end
  end
  private
  def user_params
   params.require(:user).permit(:name,:introduction,:profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
     
<div class="container">
  
  <div class="row">
    <div class="col-sm12 col-md-8 col-lg-5 px-5 mx-auto">
      <h1>Editing Book</h1>
     <% if @book.errors.any? %>
      <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
       <% end %>
      </ul>
     <% end %>
      <%= form_with model: @book do |f| %>
       <p>Title</p>
       <%=f.text_field :title %>
       <p>Opinion</p>
       <%=f.text_area :body %><br>
       <%=f.submit 'Update Book',class:'btn btn-success' %>
      <% end %>
      <%=link_to "Show",book_path(params[:id]) %> |
      <%=link_to "Back",books_path %> 
      
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
  <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
       <tbody>
        <tr>
          <th>name</th>
          <th><%=current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%=current_user.introduction %></th>
        </tr>
       </tbody>
      </table>
      <div class="row">
        <%=link_to  edit_user_path(current_user.id),class: "btn btn-outline-secondary btn-block"  do %>
         <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book do |f| %>
       <div class="form-group">
        <p>Title</p>
        <%=f.text_field :title %>
       </div>
       <div class="form-group">
         <p>Opinion</p>
         <%=f.text_area :body %><br>
       </div>
       <%=f.submit 'Create Book',class:'btn btn-success' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
            <thead>
                <tr>
                    <th></th>
                    <th>Title</th>
                    <th>Opinion</th>
                    <th colspan="3"></th>
                </tr>
            </thead>
            <tbody>
             <% @books.each do |book| %>
                <tr>
                 <td>
                  <%=link_to user_path(book.user.id) do %>
                   　<%=image_tag book.user.get_profile_image(80,80) %>
                  <% end %>
                 </td>
                 <td><%=link_to book.title,book_path(book.id) %></td>
                 <td><%=book.body %></td>
                </tr>
             <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container px-5">
 <div class="row">
   <%= render 'users/list', book: @newbook,user: @book.user %>
    <div class="col-md-8 offset-md-1">
         <h2>Book detail</h2>
        <table class="table">
            <tbody>
              <tr>
               <td>
                 <%=link_to user_path(@book.user) do %>
                   <%=image_tag @book.user.get_profile_image(100,100) %> <br>
                   <%=@book.user.name %>
                 <% end %>
               </td>
               <td><%=link_to @book.title,book_path(@book) %></td>
               <td><%=@book.body %><td>
              <%if @book.user == current_user%>
                <td><%=link_to "Edit",edit_book_path(@book),class: "btn btn-success" %></td>
                <td><%=link_to "Destroy",book_path(@book),method: :delete,data:{confirm: "本当に消しますか？"},class: "btn btn-danger"%></td>
              <% end %>
              </tr>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
       Welcome to
       <i class="fas fa-book"></i>
       <strong>Bookers !!</strong>
    </h1>
    </div>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto">
      <h1>welcome to
       <i class="fas fa-book"></i>
       <strong>Bookers !!</strong>
      </h1>
      <p>In
      <i class="fas fa-book"></i>
      <strong>Bookers,</strong>
      </p>
      <p>you can share and exchange your opinions , inpressions , and<br>
      emotions
      </p>
      <p>about various books!</p>
      <div class="btn-wrapper col-10 mx-auto ">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block sign_in" href="users/sign_in">Log in</a>
          <a class="btn btn-success btn-sm btn-block sign_up" href="users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/c33c79ba5c.js" crossorigin="anonymous"></script>
  </head>

  <body>
   <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a class="navbar-brand" href="/">
          <span>Bookers</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li>
            <%= link_to user_path(current_user),class: "nav-link text-light" do %>
              <i class="fas fa-home"></i>Home
            <% end %>
           </li>
           <li>
            <a class="nav-link text-light" href="/users">
            <i class="fas fa-users"></i>
             Users
            </a>
           </li>
           <li>
            <a class="nav-link text-light" href="/books">
            <i class="fas fa-book-open"></i>
             Books
            </a>
           </li>
           <li>
             <%= link_to destroy_user_session_path, method: :delete,class: "nav-link text-light" do %>
              <i class="fas fa-sign-out-alt"></i>Log out
             <% end %>
           </li>
          <% else %>
           <li>
            <a class="nav-link text-light" href="/">
             <i class="fas fa-home"></i>
             Home
            </a>
           </li>
           <li>
            <a class="nav-link text-light" href="/home/about">
             <i class="fas fa-link"></i>
             About
            </a>
           </li>
           <li>
            <a class="nav-link text-light" href="/users/sign_up">
             <i class="fas fa-user-plus"></i>
             Sign up
            </a>
           </li>
           <li>
            <a class="nav-link text-light" href="/users/sign_in">
             <i class="fas fa-sign-in-alt"></i>
             Log in
            </a>
           </li>
          <% end %>
          </ul>
        </div>
      </div>
    </nav>
   </header>

   <main>
    
    <%= yield %>
   </main>

   <footer>
    <div class="container mt-5">
     <div class="row">
      <div class="mx-auto">
       <p>CopyRight Infratop.inc</p>
      </div>
     </div>
    </div>
   </footer>
  </body>
</html>

app/views/users/_list.html.erb
    <div class="col-md-3">
      <h2>User info</h2>
      <!--インスタンス変数-->
      <%= image_tag user.get_profile_image(100,100) %>
      <table class="table">
       <tbody>
        <tr>
          <th>name</th>
          <th><%=user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%=user.introduction %></th>
        </tr>
       </tbody>
      </table>
      <div class="row">
        <%=link_to  edit_user_path(user),class: "col btn btn-outline-secondary btn-block"  do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
       <div class="form-group">
        <p>Title</p>
        <%=f.text_field :title %>
       </div>
       <div class="form-group">
         <p>Opinion</p>
         <%=f.text_area :body %><br>
       </div>
       <%=f.submit 'Create Book',class:'btn btn-success' %>
      <% end %>
    </div>

app/views/users/_lists.html.erb
<!--<div class="container px-5">-->
  <!--<div class="row">-->
    <div class="col-md-3">
      <h2>User info</h2>
      <%= image_tag current_user.get_profile_image(100,100) %>
      <table class="table">
       <tbody>
        <tr>
          <th>name</th>
          <th><%=current_user.name %></th>
        </tr>
        <tr>
          <th>introduction</th>
          <th><%=current_user.introduction %></th>
        </tr>
       </tbody>
      </table>
      <div class="row">
        <%=link_to  edit_user_path(current_user.id),class: "col btn btn-outline-secondary btn-block"  do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model: book do |f| %>
       <div class="form-group">
        <p>Title</p>
        <%=f.text_field :title %>
       </div>
       <div class="form-group">
         <p>Opinion</p>
         <%=f.text_area :body %><br>
       </div>
       <%=f.submit 'Create Book',class:'btn btn-success' %>
      <% end %>
    </div>
  <!--</div>-->
<!--</div>-->

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col px-5  mx-auto">
      <h2 class="mt-3">User info</h2>
    <% if @user.errors.any? %>
      <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
       <% end %>
      </ul>
    <% end %>
      <div class="col">
       <%= form_with model: @user do |f| %>
        <p>Name</p>
        <%= f.text_field :name %>
        <p>Image</p>
        <%=f.file_field :profile_image %>
        <p>Introduction</p>
        <%=f.text_area :introduction %><br>
        <%=f.submit 'Update User',class: "btn btn-secondary"%>
       <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5">

 <div class="row">
   <%= render 'users/lists', book: @book %>
    <div class="col-md-8 offset-md-1">
         <h2>Users</h2>
        <table class="table">
            <thead>
                 <tr>
                     <th>image</th>
                     <th>name</th>
                     <th colspan="3"></th>
                 </tr>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                 <tr>
                  <td><%=image_tag user.get_profile_image(80,80) %></td>
                  <td><%=user.name %></td>
                  <td><%=link_to 'Show',user_path(user.id) %></td>
                 </tr>
              <% end %>
            </tbody>
        </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5">
  <div class="row">
   <%= render 'list', book: @book,user: @user %>
    <div class="col-md-8 offset-md-1">
     <h2>Books</h2>
     <table class="table">
      <thead>
        <tr>
          <th></th>
          <th>Title</th>
          <th>Opinion</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
        <tr>
          <td>
            <%=link_to user_path(book.user) do %>
             <%=image_tag book.user.get_profile_image(80,80) %>
            <% end %>
          </td>
          <td><%=link_to book.title,book_path(book.id)%></td>
          <td><%=book.body%></td>
        </tr>
        <% end %>
      </tbody>
     </table>
    </div>
  </div>
</div>